In [1]:
import os
import pandas as pd
from datetime import datetime 
import duckdb
import unicodedata
import sys
from pathlib import Path
from kedro.framework.startup import bootstrap_project
from kedro.framework.session import KedroSession

# 1. Move to project root if we are in the notebooks folder
if Path.cwd().name == "notebooks":
    os.chdir("..")

# 2. Initialize Kedro
project_path = Path.cwd()
bootstrap_project(project_path)

# 3. Create session and get catalog
session = KedroSession.create(project_path)
context = session.load_context()
catalog = context.catalog

print(f"✅ Kedro context loaded! Project root: {project_path}")

[05/08/26 11:56:37] INFO     Using                                                                  ]8;id=888496;file://c:\Users\User\miniconda3\envs\central\Lib\site-packages\kedro\framework\project\__init__.py\__init__.py]8;;\:]8;id=927109;file://c:\Users\User\miniconda3\envs\central\Lib\site-packages\kedro\framework\project\__init__.py#269\269]8;;\
                             'c:\Users\User\miniconda3\envs\central\Lib\site-packages\kedro\framewo
                             rk\project\rich_logging.yml' as logging configuration.

[05/08/26 11:56:39] WARNING  c:\Users\User\miniconda3\envs\central\Lib\site-packages\requests\__ini ]8;id=240484;file://c:\Users\User\miniconda3\envs\central\Lib\warnings.py\warnings.py]8;;\:]8;id=386922;file://c:\Users\User\miniconda3\envs\central\Lib\warnings.py#110\110]8;;\
                             t__.py:113: RequestsDependencyWarning: urllib3 (2.6.1) or chardet
                             (6.0.0.post1)/charset_normalizer (3.4.4) doesn't match a supported
                             version!
                               warnings.warn(

[05/08/26 11:56:40] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=519897;file://c:\Users\User\miniconda3\envs\central\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=735849;file://c:\Users\User\miniconda3\envs\central\Lib\site-packages\kedro_telemetry\plugin.py#242\242]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/about/telemetry/

✅ Kedro context loaded! Project root: g:\Unidades compartidas\Alianzas\3. Data\CENTRAL\central-perm-flow

In [2]:
# Add the 'src' directory to the path
sys.path.append(os.path.abspath("src"))
import central_perm_flow.pipelines.data_processing.nodes as nodes_dproc
import central_perm_flow.pipelines.calac_activos_baj_grad.nodes as nodes_abg

# Activos

In [3]:
df_activos = catalog.load('central_activos_calendario')

[05/08/26 11:56:41] INFO     Loading data from central_activos_calendario (ParquetDataset)...  ]8;id=306743;file://c:\Users\User\miniconda3\envs\central\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=772696;file://c:\Users\User\miniconda3\envs\central\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

In [4]:
df_activos.shape

(1443, 45)

In [5]:
df_activos.loc[:,['estado','ai','engi']].value_counts().reset_index()

   estado  ai  engi  count
0  activo   1     0   1368
1  activo   0     1     75

# Graduados

In [6]:
df_graduados = catalog.load('central_graduados_calendario_academico')

                    INFO     Loading data from central_graduados_calendario_academico          ]8;id=444549;file://c:\Users\User\miniconda3\envs\central\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=426974;file://c:\Users\User\miniconda3\envs\central\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

In [9]:
df_graduados.columns

Index(['identificacion', 'codigo_sis', 'id_inconcert', 'nombres',
       'usuario_institucional', 'alianza', 'cohorte', 'fecha_ingreso',
       'fecha_de_registro', 'nivel', 'nivel_academico', 'programa', 'estado',
       'fecha_de_baja_t', 'fecha_de_baja_d', 'tipo_baja', 'motivo_baja',
       'submotivo_baja', 'comentarios', 'fecha_de_reingreso', 'fecha_grado',
       'exito_estudiantil', 'etapa_studen_journey', 'descuentos', 'di', 'gi',
       'max_semana_teorica', 'periodo_raw', 'cohorte_inicial',
       'cohorte_actual', 'bloque', 'fecha_inicio', 'fecha_fin',
       'shifted_fecha_inicio', 'semana', 'semana_acumulada', 'month',
       'mes_academico', 'anio_gregoriano', 'mes_gregoriano', 'student_journey',
       'tipo'],
      dtype='object')

In [10]:
df_graduados.loc[:,['estado','di', 'gi']].value_counts().reset_index()

                 estado  di  gi  count
0  egresado no graduado   0   1    148

# Bajas

In [11]:
df_bajas = catalog.load('central_bajas_calendario_academico')

[05/08/26 11:59:25] INFO     Loading data from central_bajas_calendario_academico              ]8;id=468565;file://c:\Users\User\miniconda3\envs\central\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=332201;file://c:\Users\User\miniconda3\envs\central\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

In [14]:
df_bajas.loc[:,['estado','di', 'gi']].value_counts().reset_index()

            estado  di  gi  count
0  baja definitiva   1   0    154
1    baja temporal   1   0     58

In [15]:
df_bajas.shape

(212, 43)